[colors]
  [colors.primary]
    background = "#10111c"  # Dark gray background
    foreground = "#abb2bf"  # Light gray foreground

[window]
  opacity = 0.95

[font]
size = 9.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

